//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, changelog not downloaded....
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debug mode.
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUI loaded.
        /// </summary>
        public static string GUILoaded {
            get {
                return ResourceManager.GetString("GUILoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch Server.
        /// </summary>
        public static string LaunchServer {
            get {
                return ResourceManager.GetString("LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading GUI....
        /// </summary>
        public static string LoadingGUI {
            get {
                return ResourceManager.GetString("LoadingGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local IP:.
        /// </summary>
        public static string LocalIP {
            get {
                return ResourceManager.GetString("LocalIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now measuring loading time.
        /// </summary>
        public static string NowMeasuringTime {
            get {
                return ResourceManager.GetString("NowMeasuringTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation completed in.
        /// </summary>
        public static string OperationCompletedIn {
            get {
                return ResourceManager.GetString("OperationCompletedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player info.
        /// </summary>
        public static string PlayerInfo {
            get {
                return ResourceManager.GetString("PlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players online.
        /// </summary>
        public static string PlayersOnline {
            get {
                return ResourceManager.GetString("PlayersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart Server.
        /// </summary>
        public static string RestartServer {
            get {
                return ResourceManager.GetString("RestartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a player first.
        /// </summary>
        public static string SelectAPlayerFirst {
            get {
                return ResourceManager.GetString("SelectAPlayerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server is already online.
        /// </summary>
        public static string ServerAlreadyOnline {
            get {
                return ResourceManager.GetString("ServerAlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server config..
        /// </summary>
        public static string ServerConfig {
            get {
                return ResourceManager.GetString("ServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The server is not running.
        /// </summary>
        public static string ServerNotRunning {
            get {
                return ResourceManager.GetString("ServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server Online.
        /// </summary>
        public static string ServerOnline {
            get {
                return ResourceManager.GetString("ServerOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Up time:.
        /// </summary>
        public static string UpTime {
            get {
                return ResourceManager.GetString("UpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Using basic performance timer.
        /// </summary>
        public static string UsingBasicTimer {
            get {
                return ResourceManager.GetString("UsingBasicTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Using high performance timer.
        /// </summary>
        public static string UsingHighTimer {
            get {
                return ResourceManager.GetString("UsingHighTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
    }
}
