
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRS.Database
{

    public class player
{

    public long PlayerId { get; set; }

    public byte AccountStatus { get; set; }

    public byte AccountPrivileges { get; set; }

    public System.DateTime LastUpdateTime { get; set; }

    public string IPAddress { get; set; }

    public string Avatar { get; set; }

    public string GameObjects { get; set; }

}

}
